import React, { useState } from "react";
import "./App.css";

function App() {
  // State for handling pop-up visibility
  const [showPopup, setShowPopup] = useState(false);

  // Function to handle the button click (show the pop-up)
  const handleCheckText = () => {
    setShowPopup(true);
    setTimeout(() => {
      setShowPopup(false); // Hide pop-up after 3 seconds
    }, 3000);
  };

  return (
    <div className="App">
      {/* Header */}
      <header className="app-header">
        <div className="logo">AI Detector</div>
        <nav>
          <button className="detect-btn">Detect AI</button>
        </nav>
      </header>

      {/* Hero Section */}
      <section className="hero">
        <div className="hero-content">
          <h1>Uncover the Origins of Text</h1>
          <p>
            Is it written by a human or generated by AI? Let our detector find
            out for you!
          </p>
        </div>
      </section>

      {/* Input Section */}
      <section className="input-section">
        <textarea
          className="text-input"
          placeholder="Paste your text here to analyze..."
        ></textarea>
        <button className="analyze-btn" onClick={handleCheckText}>
          Check Text
        </button>
      </section>

      {/* Pop-up Message */}
      {showPopup && (
        <div className="popup">
          <p>The AI model is being trained and will be deployed soon!</p>
        </div>
      )}

      {/* Footer */}
      <footer>
        <div className="footer-content">
          <p>Made with ❤️ by AI Bramwel Agina</p>
          <div className="social-links">
            <a href="https://www.linkedin.com/in/bramwel-agina-a88678266/">LinkedIn</a>
            <a href="https://bramwelagina.my.canva.site/myportofolio">My Portfolio</a>
            <a href="https://github.com/Bramtheking">GitHub</a>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default App;
